### ISSUE TITLE
segfaults

### ISSUE THREAD

**Issue by Taha-Firoz** [alanbork/rpi-opengl-without-x#1]
I don't know whats up, I'm getting a segfault when I try to run this on my [cutiepi](https://cutiepi.io/)? It's using a rpi compute module 4 and `vc4-kms-v3d-pi4 overlay` If I try to run the original on `card1` it says `Unable to get DRM resources\nUnable to get EGL display` but if I try `card0` I get a segfault

**Comment by alanbork** [comment]
This code in the version you downloaded should autodetect card0/card1 issues:

    if ((resources = drmModeGetResources(device)) == NULL) // if we have the right device we can get it's resources
        {
        printf("/dev/dri/card0 does not have DRM resources, using card1, ");
        device = open("/dev/dri/card1", O_RDWR | O_CLOEXEC); // if not, try the other one: (1)
        resources = drmModeGetResources(device);
        }
    else
      printf("using /dev/dri/card0, ");

so I suspect the issue is not card1/card2. Do you have kms/fkms enabled in /boot/config.txt?

**Comment by Taha-Firoz** [comment]
@alanbork yes sorry about this it's a firmware fault which causes the raspberry pi to faultily report an active HDMI connection even when its theres just an SPI display thats connected. The HDMI connector was the first one that came up and the code would segfault since there wasn't really an HDMI display connected. I added a check to display the types of the connectors available and just ignored the HDMI one. Thank you

**Comment by alanbork** [comment]
if you can write a version that works for both the HDMI and SPI options without recompiling I'd be interested in seeing it.

**Comment by alanbork** [comment]
even if it's not possible to make a single executable for both usage cases, it would be better if it didn't segfault. But I can't reproduce the issue so I can't change the code.
